/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPartsRouteImport } from './routes/_authenticated/parts'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedEstimatesIndexRouteImport } from './routes/_authenticated/estimates.index'
import { Route as AuthenticatedEstimatesIdRouteImport } from './routes/_authenticated/estimates.$id'
import { Route as AuthenticatedEstimatesNewRouteImport } from './routes/_authenticated/estimates.new'
import { Route as AuthenticatedFleetsIndexRouteImport } from './routes/_authenticated/fleets.index'
import { Route as AuthenticatedFleetsCustomerIdRouteImport } from './routes/_authenticated/fleets.$customerId'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalComplaintsRouteImport } from './routes/_authenticated/portal.complaints'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal.invoices'
import { Route as AuthenticatedPortalUnitsRouteImport } from './routes/_authenticated/portal.units'
import { Route as AuthenticatedUnitsIdRouteImport } from './routes/_authenticated/units.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsRoute = AuthenticatedPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedEstimatesIndexRoute =
  AuthenticatedEstimatesIndexRouteImport.update({
    id: '/estimates/',
    path: '/estimates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstimatesIdRoute =
  AuthenticatedEstimatesIdRouteImport.update({
    id: '/estimates/$id',
    path: '/estimates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstimatesNewRoute =
  AuthenticatedEstimatesNewRouteImport.update({
    id: '/estimates/new',
    path: '/estimates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFleetsIndexRoute =
  AuthenticatedFleetsIndexRouteImport.update({
    id: '/fleets/',
    path: '/fleets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFleetsCustomerIdRoute =
  AuthenticatedFleetsCustomerIdRouteImport.update({
    id: '/fleets/$customerId',
    path: '/fleets/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalComplaintsRoute =
  AuthenticatedPortalComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalUnitsRoute =
  AuthenticatedPortalUnitsRouteImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedUnitsIdRoute = AuthenticatedUnitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUnitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/units': typeof AuthenticatedUnitsRouteWithChildren
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/estimates/$id': typeof AuthenticatedEstimatesIdRoute
  '/estimates/new': typeof AuthenticatedEstimatesNewRoute
  '/fleets/$customerId': typeof AuthenticatedFleetsCustomerIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/portal/complaints': typeof AuthenticatedPortalComplaintsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/units': typeof AuthenticatedPortalUnitsRoute
  '/units/$id': typeof AuthenticatedUnitsIdRoute
  '/estimates/': typeof AuthenticatedEstimatesIndexRoute
  '/fleets/': typeof AuthenticatedFleetsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/units': typeof AuthenticatedUnitsRouteWithChildren
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/estimates/$id': typeof AuthenticatedEstimatesIdRoute
  '/estimates/new': typeof AuthenticatedEstimatesNewRoute
  '/fleets/$customerId': typeof AuthenticatedFleetsCustomerIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/portal/complaints': typeof AuthenticatedPortalComplaintsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/units': typeof AuthenticatedPortalUnitsRoute
  '/units/$id': typeof AuthenticatedUnitsIdRoute
  '/estimates': typeof AuthenticatedEstimatesIndexRoute
  '/fleets': typeof AuthenticatedFleetsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/parts': typeof AuthenticatedPartsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRouteWithChildren
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/estimates/$id': typeof AuthenticatedEstimatesIdRoute
  '/_authenticated/estimates/new': typeof AuthenticatedEstimatesNewRoute
  '/_authenticated/fleets/$customerId': typeof AuthenticatedFleetsCustomerIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/portal/complaints': typeof AuthenticatedPortalComplaintsRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/_authenticated/portal/units': typeof AuthenticatedPortalUnitsRoute
  '/_authenticated/units/$id': typeof AuthenticatedUnitsIdRoute
  '/_authenticated/estimates/': typeof AuthenticatedEstimatesIndexRoute
  '/_authenticated/fleets/': typeof AuthenticatedFleetsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/complaints'
    | '/customers'
    | '/dashboard'
    | '/parts'
    | '/portal'
    | '/reminders'
    | '/reports'
    | '/services'
    | '/settings'
    | '/units'
    | '/customers/$id'
    | '/estimates/$id'
    | '/estimates/new'
    | '/fleets/$customerId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/portal/complaints'
    | '/portal/invoices'
    | '/portal/units'
    | '/units/$id'
    | '/estimates/'
    | '/fleets/'
    | '/invoices/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/complaints'
    | '/customers'
    | '/dashboard'
    | '/parts'
    | '/reminders'
    | '/reports'
    | '/services'
    | '/settings'
    | '/units'
    | '/customers/$id'
    | '/estimates/$id'
    | '/estimates/new'
    | '/fleets/$customerId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/portal/complaints'
    | '/portal/invoices'
    | '/portal/units'
    | '/units/$id'
    | '/estimates'
    | '/fleets'
    | '/invoices'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/complaints'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/parts'
    | '/_authenticated/portal'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/units'
    | '/_authenticated/customers/$id'
    | '/_authenticated/estimates/$id'
    | '/_authenticated/estimates/new'
    | '/_authenticated/fleets/$customerId'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/portal/complaints'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/units'
    | '/_authenticated/units/$id'
    | '/_authenticated/estimates/'
    | '/_authenticated/fleets/'
    | '/_authenticated/invoices/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts': {
      id: '/_authenticated/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthenticatedPartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/estimates/': {
      id: '/_authenticated/estimates/'
      path: '/estimates'
      fullPath: '/estimates/'
      preLoaderRoute: typeof AuthenticatedEstimatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates/$id': {
      id: '/_authenticated/estimates/$id'
      path: '/estimates/$id'
      fullPath: '/estimates/$id'
      preLoaderRoute: typeof AuthenticatedEstimatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates/new': {
      id: '/_authenticated/estimates/new'
      path: '/estimates/new'
      fullPath: '/estimates/new'
      preLoaderRoute: typeof AuthenticatedEstimatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleets/': {
      id: '/_authenticated/fleets/'
      path: '/fleets'
      fullPath: '/fleets/'
      preLoaderRoute: typeof AuthenticatedFleetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleets/$customerId': {
      id: '/_authenticated/fleets/$customerId'
      path: '/fleets/$customerId'
      fullPath: '/fleets/$customerId'
      preLoaderRoute: typeof AuthenticatedFleetsCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/complaints': {
      id: '/_authenticated/portal/complaints'
      path: '/complaints'
      fullPath: '/portal/complaints'
      preLoaderRoute: typeof AuthenticatedPortalComplaintsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/units': {
      id: '/_authenticated/portal/units'
      path: '/units'
      fullPath: '/portal/units'
      preLoaderRoute: typeof AuthenticatedPortalUnitsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/units/$id': {
      id: '/_authenticated/units/$id'
      path: '/$id'
      fullPath: '/units/$id'
      preLoaderRoute: typeof AuthenticatedUnitsIdRouteImport
      parentRoute: typeof AuthenticatedUnitsRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalComplaintsRoute: typeof AuthenticatedPortalComplaintsRoute
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRoute
  AuthenticatedPortalUnitsRoute: typeof AuthenticatedPortalUnitsRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalComplaintsRoute: AuthenticatedPortalComplaintsRoute,
  AuthenticatedPortalInvoicesRoute: AuthenticatedPortalInvoicesRoute,
  AuthenticatedPortalUnitsRoute: AuthenticatedPortalUnitsRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedUnitsRouteChildren {
  AuthenticatedUnitsIdRoute: typeof AuthenticatedUnitsIdRoute
}

const AuthenticatedUnitsRouteChildren: AuthenticatedUnitsRouteChildren = {
  AuthenticatedUnitsIdRoute: AuthenticatedUnitsIdRoute,
}

const AuthenticatedUnitsRouteWithChildren =
  AuthenticatedUnitsRoute._addFileChildren(AuthenticatedUnitsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartsRoute: typeof AuthenticatedPartsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRouteWithChildren
  AuthenticatedEstimatesIdRoute: typeof AuthenticatedEstimatesIdRoute
  AuthenticatedEstimatesNewRoute: typeof AuthenticatedEstimatesNewRoute
  AuthenticatedFleetsCustomerIdRoute: typeof AuthenticatedFleetsCustomerIdRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedEstimatesIndexRoute: typeof AuthenticatedEstimatesIndexRoute
  AuthenticatedFleetsIndexRoute: typeof AuthenticatedFleetsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartsRoute: AuthenticatedPartsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRouteWithChildren,
  AuthenticatedEstimatesIdRoute: AuthenticatedEstimatesIdRoute,
  AuthenticatedEstimatesNewRoute: AuthenticatedEstimatesNewRoute,
  AuthenticatedFleetsCustomerIdRoute: AuthenticatedFleetsCustomerIdRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedEstimatesIndexRoute: AuthenticatedEstimatesIndexRoute,
  AuthenticatedFleetsIndexRoute: AuthenticatedFleetsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
